apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # Base64 encoded "root"
  MYSQL_USER: dXNlcg== # Base64 encoded "user"
  MYSQL_PASSWORD: cGFzc3dvcmQ= # Base64 encoded "password"
  MYSQL_DATABASE: Z2V0dGluZy1zdGFydGVk # Base64 for "getting-started"
